In [1]:
#import library
import pandas as pd

In [2]:
## Read data
df = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')

In [3]:
#to show all rows & colunns
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [4]:
#to show first 10 rows
df.head(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
5,Airport West,4/32 Earl St,2,t,530000.0,S,Jellis,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
6,Airport West,3/74 Hawker St,2,u,540000.0,S,Barry,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
8,Albanvale,1 Jackson Cct,6,h,NaN,PI,hockingstuart,1/04/2017,3021,Western Metropolitan,1899,14.0,Brimbank City Council
9,Albert Park,18 Mills St,3,h,1925000.0,S,Cayzer,1/04/2017,3206,Southern Metropolitan,3280,3.0,Port Phillip City Council

In [5]:
#to get the last 10 rows
df.tail(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
63013,Frankston,7 Ince Ct,5,h,710000.0,PI,hockingstuart,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63014,Frankston,1/34 Petrie St,2,u,345000.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63015,Frankston,3/34 Petrie St,2,u,340000.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63016,Frankston,4/34 Petrie St,2,u,347700.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63017,Preston,229 Murray Rd,3,h,808000.0,S,RW,31/03/2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [6]:
#to get dataset size
df.size

819299

In [7]:
#to count rows & columns
df.shape

(63023, 13)

In [8]:
#to get columns name
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Postcode', 'Regionname', 'Propertycount', 'Distance',
       'CouncilArea'],
      dtype='object')

In [9]:
#used to print a concise summary of a DataFrame
df.info

<bound method DataFrame.info of                  Suburb           Address  Rooms Type      Price Method  \
0            Abbotsford     49 Lithgow St      3    h  1490000.0      S
1            Abbotsford     59A Turner St      3    h  1220000.0      S
2            Abbotsford     119B Yarra St      3    h  1420000.0      S
3            Aberfeldie        68 Vida St      3    h  1515000.0      S
4          Airport West  92 Clydesdale Rd      2    h   670000.0      S
...                 ...               ...    ...  ...        ...    ...
63018     Roxburgh Park         3 Carr Pl      3    h   566000.0      S
63019     Roxburgh Park       9 Parker Ct      3    h   500000.0      S
63020     Roxburgh Park    5 Parkinson Wy      3    h   545000.0      S
63021        Thomastown    3/1 Travers St      3    u        NaN     PI
63022  Williams Landing       1 Diadem Wy      4    h        NaN     SP

        SellerG        Date  Postcode             Regionname  Propertycount  \
0        Jellis   1/04/2017      3067  Northern Metropolitan           4019
1      Marshall   1/04/2017      3067  Northern Metropolitan           4019
2        Nelson   1/04/2017      3067  Northern Metropolitan           4019
3         Barry   1/04/2017      3040   Western Metropolitan           1543
4        Nelson   1/04/2017      3042   Western Metropolitan           3464
...         ...         ...       ...                    ...            ...
63018     Raine  31/03/2018      3064  Northern Metropolitan           5833
63019     Raine  31/03/2018      3064  Northern Metropolitan           5833
63020     Raine  31/03/2018      3064  Northern Metropolitan           5833
63021     Barry  31/03/2018      3074  Northern Metropolitan           7955
63022    Aussie  31/03/2018      3027   Western Metropolitan           1999

       Distance                 CouncilArea
0           3.0          Yarra City Council
1           3.0          Yarra City Council
2           3.0          Yarra City Council
3           7.5  Moonee Valley City Council
4          10.4  Moonee Valley City Council
...         ...                         ...
63018      20.6           Hume City Council
63019      20.6           Hume City Council
63020      20.6           Hume City Council
63021      15.3     Whittlesea City Council
63022      17.6        Wyndham City Council

[63023 rows x 13 columns]>

In [11]:
#returns the number of missing values in the data set.
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [12]:
#to get mean 
df['Price'].mean()

997898.2414882415

In [13]:
#to get mode
df['Price'].median()

830000.0

In [15]:
#to get standard deviation
df['Price'].std()

593498.9190372757